[package]
name = "mandle_brot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speedy2d = "1.12.0"
num = "0.4.1"
futures = "0.3"
async-std = "1.12.0"